#DECK
ELEMENT_ADVANTAGES = {
    "fire": "earth",
    "earth": "water",
    "water": "fire"
}
ELEMENT_BONUS_DAMAGE = 2


#PLAYER
STANDARD_HP_PLAYER=20
STANDARD_ENERGY_PLAYER=3

NUMBER_OF_CARDS_IN_HAND=4